
all:
# g++ -g - generate debug info 
# g++ -o имя_исполняемого файла - задаем исполняемый файл, который надо указать в настройках 
# запуска отладчика vscode
	g++ Solve.cpp ReadMatrix.cpp PrintMatrix.cpp main.cpp -g -o Proga.out
ifndef CallfromVSCode
	./Proga.out 
endif
